FROM node:12
ENV PORT 3005
# create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# installing dependencies
COPY package*.json /usr/src/app/
RUN npm install
# Copy source files
COPY . /usr/src/app
# Building app
RUN npm run build
EXPOSE 3005
# Run app
CMD "npm" "run" "dev"